#!/bin/bash

# ------------------------------------------------------------------------------
# blank_dialogue.sh
#
# Usage: ./blank_dialogue.sh file.ass
#
# Description:
#   Replaces the given .ass subtitle file with:
#   - Custom metadata and two predefined styles (Default, Alt)
#   - A set of fixed chapter marker and comment events
#   - All Dialogue lines retained structurally but emptied of text
#
#   The original file is overwritten in-place.
#
# Requirements:
#   - Bash shell
#   - awk (GNU or POSIX-compatible)
#
# Example:
#   ./blank_dialogue.sh "../01/Some show - S01E01 - Dialogue.ass"
#
# Author: LightArrowsEXE
# ------------------------------------------------------------------------------

set -e

# Exit if no argument is passed
if [[ -z "$1" ]]; then
    echo "Usage: $0 file.ass"
    exit 1
fi

file="$1"
tmp="$(mktemp)"

write_metadata() {
cat <<EOF
[Script Info]
; Script generated by Aegisub 9844-cibuilds-7414b94ea
; http://www.aegisub.org/
Title: Kaleido-subs
ScriptType: v4.00+
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Export Filters: TXT Cleanup
Export Encoding: Unicode (UTF-8)
Last Style Storage: Default

[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: Default,LTFinnegan Medium,72,&H00FFFFFF,&H00FFFFFF,&H00000000,&HA0000000,0,0,0,0,100,100,0,0,1,3.6,1.5,2,200,200,60,1
Style: Alt,LTFinnegan Medium,72,&H00FFFFFF,&H00FFFFFF,&H00564100,&HA0000000,0,0,0,0,100,100,0,0,1,3.6,1.5,2,200,200,60,1

[Events]
EOF
}

write_chapter_comments() {
cat <<EOF
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,,---- Chapters
Comment: 0,0:00:00.00,0:00:00.00,Default,chapter,0,0,0,,{Intro}
Comment: 0,0:00:00.00,0:00:00.00,Default,chapter,0,0,0,,{OP}
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,opsync,{OPSync — First hard cut}
Comment: 0,0:00:00.00,0:00:00.00,Default,chapter,0,0,0,,{Part A}
Comment: 0,0:00:00.00,0:00:00.00,Default,chapter,0,0,0,,{Part B}
Comment: 0,0:00:00.00,0:00:00.00,Default,chapter,0,0,0,,{ED}
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,edsync,{EDSync — First hard cut}
Comment: 0,0:00:00.00,0:00:00.00,Default,chapter,0,0,0,,{Outro}
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,,---- Chapters
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,,---- Dialogue
Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,,---- Dialogue
EOF
}

strip_dialogue_lines() {
    awk '
    BEGIN { FS = ""; OFS = ""; in_events = 0 }

    /^\[Events\]/     { in_events = 1; next }
    /^\[/ && in_events { in_events = 0 }

    in_events && /^Dialogue:/ {
        # Find the position of the 9th comma
        comma_count = 0
        split_pos = 0
        for (i = 1; i <= length($0); i++) {
            if ($i == ",") {
                comma_count++
                if (comma_count == 9) {
                    split_pos = i
                    break
                }
            }
        }

        if (split_pos > 0) {
            # Print everything up to the 9th comma + one additional comma (for text)
            for (i = 1; i <= split_pos; i++) {
                printf "%s", $i
            }
            print ""  # newline
        } else {
            # Fallback: print original line (or skip)
            print $0
        }
    }
    ' "$file"
}

main() {
    write_metadata > "$tmp"
    write_chapter_comments >> "$tmp"
    strip_dialogue_lines >> "$tmp"

    dos2unix "$tmp" 2>/dev/null || sed -i 's/\r$//' "$tmp"

    mv "$tmp" "$file"
    echo "Blanked: $file"
}

main
